#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    __DIR__.'/vendor/autoload.php',
    __DIR__ . '/../../autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use function Innmind\Warden\bootstrap;
use Innmind\CLI\{
    Main,
    Environment,
};
use Innmind\OperatingSystem\OperatingSystem;
use Innmind\Url\Url;
use function Innmind\SilentCartographer\bootstrap as cartographer;

new class extends Main {
    protected function main(Environment $env, OperatingSystem $os): void
    {
        $os = cartographer($os)['cli'](Url::fromString(__DIR__));
        $run = bootstrap($os);
        $run($env);
    }
};
