#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    'vendor/autoload.php',
    '../autoload.php',
    __DIR__ . '/../autoload.php',
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
    getcwd() . '/vendor/autoload.php',
    getcwd() . '/../vendor/autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use function Innmind\Warden\bootstrap;
use Innmind\CLI\{
    Main,
    Environment,
};
use Innmind\OperatingSystem\OperatingSystem;

new class extends Main {
    protected function main(Environment $env, OperatingSystem $os): void
    {
        $run = bootstrap($os);
        $run($env);
    }
};
